apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: pmx1cn529-python 
  janus-idp.io/tekton: pmx1cn529-python
  backstage.io/kubernetes-id: pmx1cn529-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pmx1cn529-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml